#! /bin/bash -e

/bin/stty < /dev/ttycyan-time `cat /etc/cyan/stty.settings` || \
/bin/stty < /dev/ttycyan-time `cat /etc/cyan/stty.settings` || \
/bin/stty < /dev/ttycyan-time `cat /etc/cyan/stty.settings`
