#!/bin/bash
mkdir -p /var/volatile/overlay/ssh/ol-up/
mkdir -p /var/volatile/overlay/ssh/work/
mkdir -p /var/volatile/overlay/home/ol-up/
mkdir -p /var/volatile/overlay/home/work/

mount -t overlay -o lowerdir=/etc/ssh/,upperdir=/var/volatile/overlay/ssh/ol-up/,workdir=/var/volatile/overlay/ssh/work/ overlay /etc/ssh/
mount -t overlay -o lowerdir=/home/,upperdir=/var/volatile/overlay/home/ol-up/,workdir=/var/volatile/overlay/home/work/ overlay /home/
