#!/bin/bash

normal="\e[0m"
bold="\e[1m"

I2CBUS_ADDR=0

FANCTL1_ADDR=0x20
FANCTL2_ADDR=0x23

FANCONFIG1_ADDR=0x02
FANCONFIG2_ADDR=0x03
FANCONFIG3_ADDR=0x04
FANCONFIG4_ADDR=0x05
FANCONFIG5_ADDR=0x06
FANCONFIG6_ADDR=0x07

FANDYNAMICS1_ADDR=0x08
FANDYNAMICS2_ADDR=0x09
FANDYNAMICS3_ADDR=0x0a
FANDYNAMICS4_ADDR=0x0b
FANDYNAMICS5_ADDR=0x0c
FANDYNAMICS6_ADDR=0x0d

FANTACH1_ADDRMSB=0x18
FANTACH1_ADDRLSB=0x19
FANTACH2_ADDRMSB=0x1a
FANTACH2_ADDRLSB=0x1b
FANTACH3_ADDRMSB=0x1c
FANTACH3_ADDRLSB=0x1d
FANTACH4_ADDRMSB=0x1e
FANTACH4_ADDRLSB=0x1f
FANTACH5_ADDRMSB=0x20
FANTACH5_ADDRLSB=0x21
FANTACH6_ADDRMSB=0x22
FANTACH6_ADDRLSB=0x23

DEFAULT_FANCONFIG=0xd8
DEFAULT_FANDYNAMICS=0x8c

CONST1=60
CONST2=8192
SR=16
NP=2
case "$1" in
setup)
	i2cdetect -r -y $I2CBUS_ADDR >> /var/volatile/i2c-map
	for i in $FANCTL1_ADDR $FANCTL2_ADDR
	do
		if [[ $(cut -d\  -f2- /var/volatile/i2c-map | tail -n +2 | grep $(echo $i | cut -c 3-)) ]]
		then
			for j in $FANCONFIG1_ADDR $FANCONFIG2_ADDR $FANCONFIG3_ADDR $FANCONFIG4_ADDR $FANCONFIG5_ADDR $FANCONFIG6_ADDR
			do
				i2cset -y $I2CBUS_ADDR $i $j $DEFAULT_FANCONFIG
				#echo "i2cset -y $I2CBUS_ADDR $i $j $DEFAULT_FANCONFIG"
			done
			for k in $FANDYNAMICS1_ADDR $FANDYNAMICS2_ADDR $FANDYNAMICS3_ADDR $FANDYNAMICS4_ADDR $FANDYNAMICS5_ADDR $FANDYNAMICS6_ADDR
			do
				i2cset -y $I2CBUS_ADDR $i $k $DEFAULT_FANDYNAMICS
				#echo "i2cset -y $I2CBUS_ADDR $i $k $DEFAULT_FANDYNAMICS"
			done
		else
			echo "Missing i2c device $i"
		fi
	done
	rm /var/volatile/i2c-map
	;;
read)
	for i in $FANCTL1_ADDR $FANCTL2_ADDR
	do
		for j in $FANTACH1_ADDRLSB $FANTACH2_ADDRLSB $FANTACH3_ADDRLSB $FANTACH4_ADDRLSB $FANTACH5_ADDRLSB $FANTACH6_ADDRLSB
		do
			HEXL=$(i2cget -y $I2CBUS_ADDR $i $j | cut -c 3- | awk '{print toupper($0)}')
			#echo "VAL_LSB_HEX: $HEXL"
			ADDR_MSB=$(($j - 1))
			#echo "ADDR_MSB_DEC: $ADDR_MSB"
			ADDR_MSB_HEX=$(echo "obase=16; ibase=10; $ADDR_MSB" | bc)
			PREFIX=0x
			ADDR_MSB_HEX=$PREFIX$ADDR_MSB_HEX
			#echo "ADDR_MSB_HEX: $ADDR_MSB_HEX"
			HEXM=$(i2cget -y $I2CBUS_ADDR $i $ADDR_MSB_HEX | cut -c 3- | awk '{print toupper($0)}')
			#echo "VAL_MSB_HEX: $HEXM"
			BINM=$(echo "obase=2; ibase=16; $HEXM" | bc)
			#echo "VAL_MSB_BIN: $BINM"
			BINL=$(echo "obase=2; ibase=16; $HEXL" | bc | cut -c -3)
			if [[ "${#BINL}" == "1" ]]
			then
				PREFIX=00
				BINL=$PREFIX$BINL
			elif [[ "${#BINL}" == "2" ]]
			then
				PREFIX=0
				BINL=$PREFIX$BINL
			fi
			#echo "VAL_LSB_BIN: $BINL"
			BIN=$BINM$BINL
			#echo "VAL_BIN: $BIN"
			DEC=$(echo "obase=10; ibase=2; $BIN" | bc)
			if [[ "$DEC" == "2047" ]]
			then
				echo "Error: Chassis fan not detected"
				echo "---------------------------------------------------"
			else
				#echo "VAL_DEC: $DEC"
				let RPM="$CONST1*$CONST2*$SR/$NP/$DEC"
				echo "Fan speed in rpm: $RPM"
				echo "---------------------------------------------------"
			fi
		done
	done
	;;
*)
	echo -e "$bold Usage: ./fanctl setup|read $normal"
	echo -e "$bold setup: initialize max31790 fan controller $normal"
	echo -e "$bold read: read fan speed in rpm $normal"
	exit 1
	;;
esac
exit 0
