#! /bin/bash -e
# This script is used to help creating a tarball to bundle all the logs
# Enter ./make-tarball.sh to execute, the tarball is called log.tar.gz
SERVER_LOG=NULL
GENERAL_LOG=NULL
HOME_DIR=/home/root
if [ -e $HOME_DIR/crimson.log ];
then
	SERVER_LOG=1
else
	SERVER_LOG=0
fi
if [ "$(ls -A  $HOME_DIR/history/log)" ];
then
	GENERAL_LOG=1
else
	GENERAL_LOG=0
fi
if [ $SERVER_LOG -eq 0 -a $GENERAL_LOG -eq 0 ];
then
	echo "Nothing to pack"
	exit 0
elif [ $SERVER_LOG -eq 0 ];
then
	cd $HOME_DIR && sync && tar -zcf log.tar.gz history/log/* && echo "Packed general logs in history/log/, missing crimson.log" || echo "Packing unsuccessful"
elif [ $GENERAL_LOG -eq 0 ];
then
	cd $HOME_DIR && sync && tar -zcf log.tar.gz crimson.log && echo "Packed crimson.log, missing general logs in history/log/" || echo "Packing unsuccessful"
else
	cd $HOME_DIR && sync && tar -zcf log.tar.gz history/log/* crimson.log && echo "Packing successful" || echo "Packing unsuccessful"
fi
