#! /bin/bash -e
NOW=$(date '+%Y%m%d%H%M')
LOCATION="/var/crimson/history/log/crimson-configuration"
STRING="The package manager was setup on"
red='\e[1;31m'
normal='\e[0m'
green='\e[1;32m'
bold='\e[1m'
case "$1" in
setup)
	if [[ ! -z $(grep "$STRING" "$LOCATION") ]];
	then
		echo "$(grep "$STRING" "$LOCATION")"
		echo "Use ./package-manager update to update the server ip address"
		exit 1
	fi
	read -r -p "What is the server ip address? `echo $'\n> '`" ADD
	if [[ $ADD =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		for i in `seq 1 4`; do
			if [ $(echo "$ADD" | cut -d. -f$i) -gt 255 ]; then
				echo -e "[$red FAILED $normal] Invalid ip address, please try again"
				exit 1
			fi
		done
		echo "Attempting to setup package manager's server ip addres to $ADD on $NOW" >> $LOCATION
		echo "[        ] Attempting to setup package manager's server ip address..."
		smart channel --yes --add all type=rpm-md name=all baseurl=http://$ADD/crimson/all > /dev/null
		smart channel --yes --add cortexa9hf_vfp_neon type=rpm-md name=cortexa9hf_vfp_neon baseurl=http://$ADD/crimson/cortexa9hf_vfp_neon > /dev/null
		smart channel --yes --add arria5 type=rpm-md name=arria5 baseurl=http://$ADD/crimson/arria5 > /dev/null
		echo "The package manager was setup on $NOW with the server ip address set to $ADD" >> $LOCATION
		echo -e "[$green   OK   $normal] Successfully setup the package manager's server ip address"
	else
		echo -e "[$red FAILED $normal] Invalid ip address, please try again"
		exit 1
	fi
	;;
update)
	read -r -p "What is the new server ip address? `echo $'\n> '`" NEW_ADD
	if [[ $NEW_ADD =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		for i in `seq 1 4`; do
			if [ $(echo "$NEW_ADD" | cut -d. -f$i) -gt 255 ]; then
				echo -e "[$red FAILED $normal] Invalid ip address, please try again"
				exit 1
			fi
		done
		echo "Attempting to update package manager's server ip address to $NEW_ADD on $NOW" >> $LOCATION
		echo "[        ] Attempting to update package manager's server ip address..."
		smart channel --yes --remove-all > /dev/null
		smart channel --yes --add all type=rpm-md name=all baseurl=http://$NEW_ADD/crimson/all > /dev/null
		smart channel --yes --add cortexa9hf_vfp_neon type=rpm-md name=cortexa9hf_vfp_neon baseurl=http://$NEW_ADD/crimson/cortexa9hf_vfp_neon > /dev/null
		smart channel --yes --add arria5 type=rpm-md name=arria5 baseurl=http://$NEW_ADD/crimson/arria5 > /dev/null
		echo "The package manager was updated on $NOW with the server ip address set to $NEW_ADD" >> $LOCATION
		echo -e "[$green   OK   $normal] Successfully updated the package manager's server ip address"
	else
		echo -e "[$red FAILED $normal] Invalid ip address, please try again"
		exit 1
	fi
	;;
*)
	echo -e "$bold Usage: /etc/init.d/package-manager {setup|update} $normal"
	echo -e "$bold Setup: Setup the server ip address used by package manger $normal"
	echo -e "$bold Update: Update the server ip address used by package manager $normal"
	exit 1
	;;
esac

exit 0
